In [27]:
import numpy as np
import scipy.signal

## Question 1

The code below shows the convolution between the array b# and kernel a#.

In [28]:
a1 = np.array([1,2,1])
b1 = np.array([2, 2, 3, 3, 2])

a2 = np.array([1,1,3,1,1])
b2 = np.array([3, 3, -2, -1, 0, 1, 2, 3, 3])

a3 = np.array([[-1,0,1],
               [-2,0,2],
               [-1,0,1]])
b3 = np.array([[0,  5,  5,  5, 0],
               [0,  5, 10,  5, 0],
               [0, 10, 10, 10, 0],
               [0,  5, 10,  5, 0],
               [0,  5,  5,  5, 0]])

print(np.convolve(b1, a1, mode='valid'))
print(np.convolve(b2, a2, mode='valid'))
print(scipy.signal.convolve2d(a3, b3, mode='valid'))

[ 9 11 11]
[-1 -1  0  7 13]
[[-35   0  35]
 [-40   0  40]
 [-35   0  35]]


## Question 2

To implement low pass filtering in the Fourier domain a new function H(u, v) needs to be defined. F(u, v)H(u, v)=G(u, v). H(u, v) will contain a circle of values of 1 near the origin and then 0 outside that circle. The radius of this circle is the cut-off radius.

**Butterworth's low pass filter, or Gaussian filtering**

## Question 3

Fourier transforms contains information on different properties of an image:
- To extract the low frequency regions, take the region within a set radius of the origin.
- To extract the high frequency regions with intensity variations 45 degrees to the horizontal, take an arc around 45 degrees to the horizontal that is outside a set radius of the origin.
- To extract the mid-frequency regions, take a ring of the space that is between two set radii.

## Question 4

### Part A

Colour, contrast, size, roundness. The colour alone would not be able to match these particular fruits as they have similar colour, but it will help with classification. Contrast would work similar to colour, this would be taken from the center of the fourier transform. Roundness can be measured by comparing how rotationally symmetric the fourier transform and would work well at comparing the Red Pears to the other fruits. Size would work well at comparing Satsumas and Oranges.

### Part B

Using a test sample of the mixed fruits, a test set of data could be acquired for each of the 20 features. The covariance matrix can be produced from this data. The corresponding eigenvalues are proportional to how much each feature contributes to total variance. Remove all features which have an insignificant effect on total variance.

## Question 5

B is correct

## Question 6

C, 1/24

## Question 7

D, 92.3%